### ISSUE TITLE
Issue with weight initialization of GPT model

### ISSUE THREAD

**Issue by Dakingrai** [Pascalson/LERG#1]
python explain.py LERG_S <model-dir> <data-path>

Returns the warning message and terminates the program:

Some weights of the model checkpoint at models/dailydialog_gpt were not used when initializing OpenAIGPTLMHeadModel: ['multiple_choice_head.summary.weight', 'multiple_choice_head.summary.bias']
- This IS expected if you are initializing OpenAIGPTLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing OpenAIGPTLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Killed

**Comment by Pascalson** [comment]
Thank you for indicating this.

The warning happens since I initialized the model with DoubleHeadsModel. I have uploaded a new model to the drive which does not have the two redundant weights. The warnings should not happen if using the new model.

On my side, even getting the warnings, the program will not be terminated.
If still getting problem, please tell me. Thanks!

**Comment by Dakingrai** [comment]
Thank you for the reply and for uploading the new model. 

Yeah, termination was due to another issue with my setup. It's now resolved and all is good. I'll try the new model as well. 

Thank you, again :)

**Comment by Pascalson** [comment]
No problem!
